### ISSUE TITLE
What a job!

### ISSUE THREAD

**Issue by alexruben007** [alnutile/larachain#7]
What a job! Well done! I've been looking for exactly that in laravel for a while now, bummed out by all the production in python and node.js.

All this documentation, you are really an experienced coder and this project is awesome.

I'm too bad a coder to help you but passionate and knowledgeable enough about the technique, I will seriously follow the project and try to test it quickly.

If you want to add more databases, there is a php class to connect the pinecone API which seems to be a must. But I like the idea of using an OpenSource DB. https://github.com/probots-io/pinecone-php

Otherwise, as far as langchain php is concerned, Kambo has already made a lot of progress on the https://github.com/kambo-1st/langchain-php project, I think it includes things that will interest you.

**Comment by alnutile** [comment]
Thanks! That database keeps coming up I will for sure try it and document the use. Sent from my iPhoneOn May 16, 2023, at 7:54 PM, Alex Ruben ***@***.***> wrote:﻿
What a job! Well done! I've been looking for exactly that in laravel for a while now, bummed out by all the production in python and node.js.
All this documentation, you are really an experienced coder and this project is awesome.
I'm too bad a coder to help you but passionate and knowledgeable enough about the technique, I will seriously follow the project and try to test it quickly.
If you want to add more databases, there is a php class to connect the pinecone API which seems to be a must. But I like the idea of using an OpenSource DB. https://github.com/probots-io/pinecone-php

**Comment by alnutile** [comment]
moved to project https://github.com/users/alnutile/projects/2?pane=issue&itemId=29196006
